### ISSUE TITLE
Sort rides on user profile page by start date, not by creation date

### ISSUE THREAD

**Issue by serge1peshcoff** [flov/Hitchlog#13]
My case: when I was adding my rides after registration, I did it not in the right order (e.g. I've added a trip that happened 2 years ago, then 1 year ago, then 3 years ago etc.), and now the rides block on my profile page looks like this:
![image](https://user-images.githubusercontent.com/1060257/29861472-0a6ec4fc-8d72-11e7-9d86-fc6c1347dbb6.png)

It would make more sense to sort them by ride's start date rather then by creation date (like it is now, I suppose).

**Comment by serge1peshcoff** [comment]
The solution for this, AFAIK, would be just changing the `UsersController`'s `show` method and add `order` call on the second like of the method.

@flov What do you think about it?

**Comment by flov** [comment]
Hi Sergey!
Great remark! I think you're right. This is a very easy task. I'll do it once I've got a bit time on my hands. Thanks. Flo

**Comment by flov** [comment]
that's correct :) I will update it and push it to production.

**Comment by serge1peshcoff** [comment]
Yay, I already see that this is working, seems better than it was before!
Thanks @flov

**Comment by serge1peshcoff** [comment]
Forgot to close it, sorry.
